# Enables Version 3 initial-state bootstrap.
# This profile should be activated only when we explicitly want to initialize the system from a file.

ticketsystem.initial-state.enabled=true

# External initial-state file.
# The default is config/initial-state-v3.json in the project root.
# Can be overridden with:
# export INITIAL_STATE_FILE="file:/absolute/path/to/initial-state.json"

ticketsystem.initial-state.file=${INITIAL_STATE_FILE:file:./config/initial-state-v3.json}