package ticketsystem.DomainLayer.history;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OrderColumn;
import jakarta.persistence.Table;


/**
 * Aggregate root representing an immutable snapshot of a completed purchase.
 *
 * <p>The purchase stores historical values such as the event name, location,
 * ticket prices and company identifiers. These values are intentionally not
 * mapped as JPA relationships to the live event, company or member entities.
 * Therefore, later changes to those entities do not change purchase history.</p>
 *
 * <p>The purchase identifier is generated by the database. The constructors
 * that accept an explicit identifier are retained temporarily while the
 * existing in-memory history repository and tests are migrated to JPA.</p>
 */
@Entity
@Table(
        name = "purchases",
        indexes = {
                @Index(
                        name = "idx_purchases_member_id",
                        columnList = "member_id"
                ),
                @Index(
                        name = "idx_purchases_company_id",
                        columnList = "company_id"
                ),
                @Index(
                        name = "idx_purchases_event_id",
                        columnList = "event_id"
                ),
                @Index(
                        name = "idx_purchases_manager_id",
                        columnList = "managed_by_member_id"
                )
        }
)
public class Purchase {

    /**
     * Database-generated purchase identifier.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "purchase_id")
    private Long purchaseId;

    /**
     * Purchased ticket snapshots belonging to this purchase.
     *
     * <p>The tickets are stored in a separate collection table, but they are
     * still part of the Purchase aggregate and have no independent
     * repository.</p>
     */
    @ElementCollection(fetch = FetchType.LAZY)
    @CollectionTable(
            name = "purchased_tickets",
            joinColumns = @JoinColumn(
                    name = "purchase_id",
                    nullable = false
            )
    )
    @OrderColumn(name = "ticket_index")
    private List<PurchasedTicket> tickets = new ArrayList<>();

    /**
     * Event name captured at the time of purchase.
     */
    @Column(name = "event_name", nullable = false, length = 255)
    private String eventName;

    /**
     * Event location captured at the time of purchase.
     */
    @Column(name = "location", nullable = false, length = 255)
    private String location;

    /**
     * Buyer member identifier.
     *
     * <p>This value is nullable because guests may complete purchases.</p>
     */
    @Column(name = "member_id")
    private Long memberId;

    /**
     * Production company identifier captured at purchase time.
     */
    @Column(name = "company_id", nullable = false)
    private Long companyId;

    /**
     * Member who managed or created the relevant event.
     */
    @Column(name = "managed_by_member_id")
    private Long managedByMemberId;

    /**
     * Original event identifier captured at purchase time.
     */
    @Column(name = "event_id", nullable = false)
    private Long eventId;

    /**
     * Total amount paid for the purchase.
     */
    @Column(
            name = "total_price",
            nullable = false,
            precision = 19,
            scale = 2
    )
    private BigDecimal totalPrice;

    /**
     * Identifier returned by the external payment system.
     */
    @Column(name = "transaction_id")
    private Integer transactionId;

    /**
     * Indicates whether this purchase has already been refunded.
     */
    @Column(name = "refunded", nullable = false)
    private boolean refunded;


    /**
     * Constructor required by JPA and temporarily by the existing DTO mapper.
     */
    public Purchase() {
        this.tickets = new ArrayList<>();
        this.refunded = false;
    }

    /**
     * Creates a new purchase without a manually assigned identifier.
     *
     * <p>This is the constructor that production code will use after the
     * explicit history mapper is introduced. The database assigns the ID when
     * the purchase is persisted.</p>
     *
     * @param tickets purchased-ticket snapshots
     * @param eventName event name at purchase time
     * @param location event location at purchase time
     * @param memberId buyer member ID, or {@code null} for a guest
     * @param companyId production company ID
     * @param managedByMemberId event manager or creator ID
     * @param eventId original event ID
     * @param totalPrice total purchase price
     * @param transactionId external payment transaction ID
     */
    public Purchase(
            List<PurchasedTicket> tickets,
            String eventName,
            String location,
            Long memberId,
            Long companyId,
            Long managedByMemberId,
            Long eventId,
            BigDecimal totalPrice,
            Integer transactionId
    ) {
        this(
                null,
                tickets,
                eventName,
                location,
                memberId,
                companyId,
                managedByMemberId,
                eventId,
                totalPrice,
                transactionId
        );
    }

    /**
     * Creates a new purchase without a payment transaction identifier.
     *
     * @param tickets purchased-ticket snapshots
     * @param eventName event name at purchase time
     * @param location event location at purchase time
     * @param memberId buyer member ID, or {@code null} for a guest
     * @param companyId production company ID
     * @param managedByMemberId event manager or creator ID
     * @param eventId original event ID
     * @param totalPrice total purchase price
     */
    public Purchase(
            List<PurchasedTicket> tickets,
            String eventName,
            String location,
            Long memberId,
            Long companyId,
            Long managedByMemberId,
            Long eventId,
            BigDecimal totalPrice
    ) {
        this(
                tickets,
                eventName,
                location,
                memberId,
                companyId,
                managedByMemberId,
                eventId,
                totalPrice,
                null
        );
    }

    /**
     * Temporary compatibility constructor that accepts an explicit purchase ID.
     *
     * <p>This constructor will be removed after the history repository and
     * tests are migrated to database-generated identifiers.</p>
     *
     * @param purchaseId temporary manually assigned purchase identifier
     * @param tickets purchased-ticket snapshots
     * @param eventName event name at purchase time
     * @param location event location at purchase time
     * @param memberId buyer member ID, or {@code null}
     * @param companyId production company ID
     * @param managedByMemberId event manager or creator ID
     * @param eventId original event ID
     * @param totalPrice total purchase price
     */
    public Purchase(
            Long purchaseId,
            List<PurchasedTicket> tickets,
            String eventName,
            String location,
            Long memberId,
            Long companyId,
            Long managedByMemberId,
            Long eventId,
            BigDecimal totalPrice
    ) {
        this(
                purchaseId,
                tickets,
                eventName,
                location,
                memberId,
                companyId,
                managedByMemberId,
                eventId,
                totalPrice,
                null
        );
    }

    /**
     * Temporary compatibility constructor that accepts an explicit purchase ID.
     *
     * <p>Production persistence must ultimately use the constructor without an
     * ID and allow the database to generate it.</p>
     *
     * @param purchaseId temporary manually assigned purchase identifier
     * @param tickets purchased-ticket snapshots
     * @param eventName event name at purchase time
     * @param location event location at purchase time
     * @param memberId buyer member ID, or {@code null}
     * @param companyId production company ID
     * @param managedByMemberId event manager or creator ID
     * @param eventId original event ID
     * @param totalPrice total purchase price
     * @param transactionId external payment transaction ID
     */
    public Purchase(
            Long purchaseId,
            List<PurchasedTicket> tickets,
            String eventName,
            String location,
            Long memberId,
            Long companyId,
            Long managedByMemberId,
            Long eventId,
            BigDecimal totalPrice,
            Integer transactionId
    ) {
        this.purchaseId = purchaseId;
        this.tickets = new ArrayList<>();

        setEventName(eventName);
        setLocation(location);

        this.memberId = memberId;
        this.companyId = Objects.requireNonNull(
                companyId,
                "Company ID cannot be null."
        );

        this.managedByMemberId = managedByMemberId;

        this.eventId = Objects.requireNonNull(
                eventId,
                "Event ID cannot be null."
        );

        setTotalPrice(totalPrice);

        this.transactionId = transactionId;
        this.refunded = false;

        if (tickets != null) {
            tickets.forEach(this::addTicket);
        }
    }

    /**
     * Adds a ticket snapshot to this purchase.
     *
     * @param ticket ticket snapshot to add
     */
    public void addTicket(PurchasedTicket ticket) {
        this.tickets.add(
                Objects.requireNonNull(
                        ticket,
                        "Purchased ticket cannot be null."
                )
        );
    }

    /**
     * Returns the database-generated purchase identifier.
     *
     * @return purchase identifier, or {@code null} before persistence
     */
    public Long getPurchaseId() {
        return purchaseId;
    }

    /**
     * Temporarily assigns a purchase identifier.
     *
     * <p>This method exists only while the old in-memory ID generation is being
     * removed. Production code must not assign database identifiers manually.</p>
     *
     * @param purchaseId purchase identifier
     */
    public void setPurchaseId(Long purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * Returns the external payment transaction identifier.
     *
     * @return transaction identifier
     */
    public Integer getTransactionId() {
        return transactionId;
    }

    /**
     * Returns the buyer member identifier.
     *
     * @return member identifier, or {@code null} for a guest
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * Returns the production company identifier.
     *
     * @return company identifier
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * Returns the event manager or creator identifier.
     *
     * @return manager identifier
     */
    public Long getManagedByMemberId() {
        return managedByMemberId;
    }

    /**
     * Returns the historical event name.
     *
     * @return event name
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * Updates the historical event name.
     *
     * @param eventName event name
     */
    public void setEventName(String eventName) {
        if (eventName == null || eventName.isBlank()) {
            throw new IllegalArgumentException(
                    "Event name cannot be blank."
            );
        }

        this.eventName = eventName;
    }

    /**
     * Returns the historical event location.
     *
     * @return event location
     */
    public String getLocation() {
        return location;
    }

    /**
     * Updates the historical event location.
     *
     * @param location event location
     */
    public void setLocation(String location) {
        if (location == null || location.isBlank()) {
            throw new IllegalArgumentException(
                    "Event location cannot be blank."
            );
        }

        this.location = location;
    }

    /**
     * Returns the original event identifier.
     *
     * @return event identifier
     */
    public Long getEventId() {
        return eventId;
    }

    /**
     * Returns a defensive copy of the purchased-ticket list.
     *
     * <p>The list itself cannot be modified from outside the aggregate. The
     * ticket objects remain managed parts of the purchase, so status updates
     * performed inside a transaction are still detected by Hibernate.</p>
     *
     * @return defensive ticket list
     */
    public List<PurchasedTicket> getTickets() {
        return new ArrayList<>(tickets);
    }

    /**
     * Returns the total purchase price.
     *
     * @return total purchase price
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * Updates the total purchase price.
     *
     * @param totalPrice non-negative total price
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        if (totalPrice == null) {
            throw new IllegalArgumentException(
                    "Total purchase price cannot be null."
            );
        }

        if (totalPrice.signum() < 0) {
            throw new IllegalArgumentException(
                    "Total purchase price cannot be negative."
            );
        }

        this.totalPrice = totalPrice;
    }

    /**
     * Indicates whether the purchase has been refunded.
     *
     * @return {@code true} when the purchase was refunded
     */
    public boolean isRefunded() {
        return refunded;
    }

    /**
     * Updates the refund state.
     *
     * @param refunded new refund state
     */
    public void setRefunded(boolean refunded) {
        this.refunded = refunded;
    }

}