package ticketsystem.DomainLayer.lottery;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MapKey;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

/**
 * Aggregate root representing a purchase lottery associated with an event.
 *
 * <p>The lottery owns all registrations made for it. Registrations are
 * therefore created and updated only through this aggregate.</p>
 *
 * <p>The lottery identifier is generated by the database. The event is
 * represented by its scalar identifier so that the Lottery persistence model
 * does not depend on the Event module already being migrated to JPA.</p>
 */
@Entity
@Table(
        name = "lotteries",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_lottery_event",
                        columnNames = "event_id"
                )
        }
)
public class Lottery {

    /**
     * Database-generated lottery identifier.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "lottery_id")
    private Long lotteryId;

    /**
     * Optimistic-locking version used to detect conflicting updates to the
     * same lottery.
     */
    @Version
    @Column(name = "version", nullable = false)
    private Long version;

    /**
     * Identifier of the event associated with this lottery.
     */
    @Column(name = "event_id", nullable = false)
    private Long eventId;

    /**
     * Number of participants that may be selected as winners.
     */
    @Column(name = "winners_number", nullable = false)
    private int winnersNumber;

    /**
     * Current lifecycle state of the lottery.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private LotteryStatus status;

    /**
     * Registrations owned by this lottery and indexed by member identifier.
     *
     * <p>Cascade persistence stores registrations together with their lottery.
     * Orphan removal ensures that a registration removed from the aggregate is
     * also removed from the database.</p>
     */
    @OneToMany(
            mappedBy = "lottery",
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.LAZY
    )
    @MapKey(name = "memberId")
    private Map<Long, LotteryRegistration> registrations = new HashMap<>();

    /**
     * Required by JPA.
     */
    protected Lottery() {
    }

    /**
     * Creates a new lottery.
     *
     * <p>The identifier is intentionally not accepted by this constructor,
     * because it is assigned by the database when the lottery is persisted.</p>
     *
     * @param eventId       associated event identifier
     * @param winnersNumber number of winners to select
     */
    public Lottery(long eventId, int winnersNumber) {
        this.eventId = eventId;
        this.winnersNumber = winnersNumber;
        this.status = LotteryStatus.OPEN;
        this.registrations = new HashMap<>();
    }

    public Long getLotteryId() {
        return lotteryId;
    }

    public Long getVersion() {
        return version;
    }

    public long getEventId() {
        return eventId;
    }

    public void setEventId(long eventId) {
        this.eventId = eventId;
    }

    public int getWinnersNumber() {
        return winnersNumber;
    }

    public void setWinnersNumber(int winnersNumber) {
        this.winnersNumber = winnersNumber;
    }

    public LotteryStatus getStatus() {
        return status;
    }

    public void setStatus(LotteryStatus status) {
        this.status = status;
    }

    /**
     * Returns a defensive snapshot of all lottery registrations.
     *
     * @return copied registration list
     */
    public List<LotteryRegistration> getRegistrations() {
        return new ArrayList<>(registrations.values());
    }

    /**
     * Returns all members selected as winners.
     *
     * @return winner member identifiers
     */
    public List<Long> getWinners() {
        return registrations.values()
                .stream()
                .filter(LotteryRegistration::isWinner)
                .map(LotteryRegistration::getMemberId)
                .collect(Collectors.toList());
    }

    /**
     * Registers a member to this lottery.
     *
     * @param memberId member attempting to register
     * @throws IllegalStateException if registration is closed or the member is
     *                               already registered
     */
    public void registerMember(long memberId) {
        if (status != LotteryStatus.OPEN) {
            throw new IllegalStateException(
                    "Registration is closed for this lottery."
            );
        }

        if (registrations.containsKey(memberId)) {
            throw new IllegalStateException(
                    "Member is already registered for this lottery."
            );
        }

        LotteryRegistration registration =
                new LotteryRegistration(this, memberId);

        registrations.put(memberId, registration);
    }

    /**
     * Returns all registered member identifiers.
     *
     * @return copied list of registered member identifiers
     */
    public List<Long> getRegisteredMemberIds() {
        return new ArrayList<>(registrations.keySet());
    }

    /**
     * Marks a registered member as a winner.
     *
     * @param memberId member selected as a winner
     * @param authCode authentication code generated for that member
     * @throws IllegalArgumentException if the member is not registered
     */
    public void setWinner(long memberId, String authCode) {
        LotteryRegistration registration = registrations.get(memberId);

        if (registration == null) {
            throw new IllegalArgumentException(
                    "Member ID not found in registrations."
            );
        }

        registration.markAsWinner(authCode);
    }

    /**
     * Validates that a submitted code belongs to the specified winning member.
     *
     * @param memberId  member attempting to use the code
     * @param inputCode submitted authentication code
     * @return true when the member won and the code matches
     */
    public boolean validateWinnerCode(
            long memberId,
            String inputCode
    ) {
        LotteryRegistration registration = registrations.get(memberId);

        if (registration == null || !registration.isWinner()) {
            return false;
        }

        return inputCode.equals(registration.getAuthCode());
    }
}